const IMAGES = {
  SPLASH_IMAGE: require('../assets/images/splashman.png'),
  BACKGROUND_IMAGE: require('../assets/images/background.png'),
  FIVE_IMAGE: require('../assets/images/five.png'),
  STAR_IMAGE: require('../assets/images/star.png'),
  GOOGLE_IMAGE: require('../assets/images/google.png'),
  APPLE_IMAGE: require('../assets/images/apple.png'),
  EYE_CLOSE_IMAGE: require('../assets/images/eye.png'),
  EYE_OPEN_IMAGE: require('../assets/images/Vector.png'),
  BACK_IMAGE: require('../assets/images/VectorBack.png'),
  CHECKBOX_IMAGE: require('../assets/images/checkbox.png'),
  CHECKBOX_ENABLE: require('../assets/images/checkbox1.png'),
  TIMER_PIC: require('../assets/images/Timerimg.png'),
  FAN_IMAGE: require('../assets/images/fan.png'),
  PLAYER_IMAGE: require('../assets/images/player.png'),
  RIGHT_THUMB: require('../assets/images/rightthumb.png'),
  COVER_IMAGE: require('../assets/images/newcover.png'),
  GROUP_IMAGE: require('../assets/images/group.png'),
  RIGHT_CONGRATULATION: require('../assets/images/rightthumb.png'),
  CAMERA: require('../assets/images/camera.png'),
  DATE: require('../assets/images/date.png'),
  RIGHT: require('../assets/images/rightvector.png'),
  CROSS_IMAGE: require('../assets/images/crossimage.png'),
  Tick_IMAGE: require('../assets/images/tick.png'),
  Boxer_IMAGE: require('../assets/images/Boxer.png'),
  FOOTER_IMAGE: require('../assets/images/fotterimage.png'),
  NAME_ARROW: require('../assets/images/namearrow.png'),
  SEARCH_IMAGE: require('../assets/images/search.png'),
  CROSS_SPORT_IMAGE: require('../assets/images/crossimg.png'),
};
export default IMAGES;
